# Generated by Django 5.0 on 2023-12-15 11:00

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_polygon_customuser_highlighted_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='highlighted_area',
        ),
        migrations.AddField(
            model_name='customuser',
            name='polygons',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, geography=True, help_text='Point(longitude latitude)', null=True, srid=4326, verbose_name='Location in Map'),
        ),
        migrations.DeleteModel(
            name='PolygonModel',
        ),
    ]
