# Generated by Django 5.0 on 2023-12-15 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_highlighted_area_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='polygons',
            new_name='highlighted_area',
        ),
    ]
